import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await (await b.newContext({storageState:'_e2e/agency_state.json'})).newPage();
await p.goto('http://localhost:3000/agency/account',{waitUntil:'networkidle',timeout:30000});
await p.waitForTimeout(1200);
await p.fill('input[placeholder="e.g. City Express (Bus)"]','Demo Bus Service');
await p.fill('textarea[placeholder^="Tell the admin"]','Daily campus bus for LJ University. 40-seat AC, morning+evening.');
await p.locator('button:has-text("Select a school/college")').click();
await p.waitForTimeout(800);
await p.keyboard.type('LJ'); await p.waitForTimeout(1500);
const cand=p.getByText(/LJ University/i).first();
const picked=await cand.count()>0;
if(picked) await cand.click();
await p.keyboard.press('Escape'); await p.waitForTimeout(400);
// Bus toggle state
const busBtn=p.locator('button:has-text("Bus")').last();
const pressed=await busBtn.getAttribute('aria-pressed').catch(()=>null);
console.log('college picked:',picked,' bus aria-pressed:',pressed);
if(pressed==='false') await busBtn.click();
await p.waitForTimeout(300);
await p.locator('button:has-text("Submit request")').click();
await p.waitForTimeout(4500);
const st=await p.evaluate(()=>({url:location.href, txt:document.body.innerText.replace(/\s+/g,' ')}));
const msg=st.txt.match(/(pending|submitted|request[^.]{0,60}|already[^.]{0,60}|error[^.]{0,60}|awaiting[^.]{0,60})/i);
console.log('URL:',st.url);
console.log('MSG:',msg?msg[0]:'(none)');
await p.screenshot({path:'_e2e/agency_service_req.png',fullPage:true});
await b.close();
