import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await (await b.newContext({storageState:'_e2e/agency_state.json'})).newPage();
await p.goto('http://localhost:3000/agency/drivers',{waitUntil:'networkidle',timeout:30000});
await p.waitForTimeout(1000);
const set=async(n,v)=>{const el=await p.$(`input[name=${n}]`); if(el) await el.fill(v);};
await set('name','Demo Driver');
await set('phone','9876500002');
await set('email','infinite.storage13013+driver@gmail.com');
await set('password','DemoPass123!');
await set('licenseNo','GJ0120210009999');
await set('aadhaarNo','1111 2222 3333');
await set('altPhone','9876500003');
await set('address','5 Depot Lane, Ahmedabad');
await set('dob','1990-05-15');
await set('bloodGroup','O+');
await p.screenshot({path:'_e2e/driver_form.png',fullPage:true});
await p.getByRole('button',{name:/create driver account/i}).click();
await p.waitForTimeout(6000);
const st=await p.evaluate(()=>({url:location.href, txt:document.body.innerText.replace(/\s+/g,' ')}));
const msg=st.txt.match(/(created|added|success|error[^.]{0,80}|already[^.]{0,80}|invalid[^.]{0,80}|Demo Driver)/i);
console.log('URL:',st.url); console.log('MSG:',msg?msg[0]:'(none)');
await p.screenshot({path:'_e2e/driver_created.png',fullPage:true});
await b.close();
